disabled_rules:
  - line_length
  - orphaned_doc_comment

cyclomatic_complexity:
  ignores_case_statements: true

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - vendor
  - Pods
  - Podfile
  - Podfile.lock

identifier_name:
  excluded:
    - id
    - io
    - on
    - of

force_try:
  severity: warning
