disabled_rules:
  - line_length
  - orphaned_doc_comment
  - nesting

cyclomatic_complexity:
  ignores_case_statements: true

identifier_name:
  excluded:
    - id
    - io
    - on
    - of
    - db

force_try:
  severity: warning
