name: Deploy GitHub Pages

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/gh-pages.yml
      - privacy-policy/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/gh-pages.yml
      - privacy-policy/**

concurrency:
  group: publishing-pages-${{ github.ref_name }}
  cancel-in-progress: true

# FIXME: replace ~Date~
# FIXME: insert css

jobs:
  render:
    name: Render pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup markdown
        shell: bash
        run: pipx install markdown
      - name: Prepare output directories
        shell: bash
        run: mkdir -p output/privacy-policy
      - name: Convert markdowns
        shell: bash
        run: markdown_py privacy-policy/index.md > output/privacy-policy/index.html
      - name: Copy stylesheets
        shell: bash
        run: find privacy-policy -type f -name '*.css' -print0 | rsync -av --files-from=- --from0 . output/
      - name: Prepare artifact
        shell: bash
        run: chmod +rx output
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

  deploy:
    needs: render
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
