name: lane

on:
  workflow_call: {}

jobs:
  lane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install lane
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version=$(grep lane .tool-versions | cut -d\  -f2)
          echo "Using lane version: $version"
          gh release download "$version" --repo CodeReaper/lane
          tar -xJv -C /usr/local/bin --exclude LICENSE.txt < "lane-$version.tar.xz"
          git clean -fdx .
          git diff-index --quiet HEAD --
      - run: lane update-licenses
      - run: lane update-translations
      - name: Verify no changes
        run: |
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo "::group::Uncommitted changes"
            git status
            echo "::endgroup::"
            exit 1
          fi
