name: lane

on:
  workflow_call: {}

jobs:
  lane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install lane
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version=$(grep lane .tool-versions | cut -d\  -f2)
          echo "Using lane version: $version"
          gh release download "$version" --repo CodeReaper/lane
          tar -xJv -C /usr/local/bin --exclude LICENSE.txt < "lane-$version.tar.xz"
          git clean -fdx .
          git diff-index --quiet HEAD --
      - shell: bash
        run: lane images
      - shell: bash
        run: lane update-licenses
      - shell: bash
        run: lane update-translations
      - name: Verify no changes
        shell: bash
        run: git diff-index --quiet HEAD --
      - name: Print error details
        shell: bash
        if: failure()
        run: |
          echo "::group::Uncommitted changes:"
          git diff HEAD --
          echo "::endgroup::"
