name: Editorconfig

on:
  pull_request: {}

jobs:
  validate:
    name: Editorconfig validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  tests-succeeded:
    runs-on: macos-latest
    needs: validate
    name: Tests Succeeded
    steps:
      - name: Succeed
        run: exit 0
