name: Swiftlint

on:
  workflow_call: {}

jobs:
  validate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: swiftlint --strict --config .swiftlint.ci.yml --config .swiftlint.yml
