name: Tests

on:
  pull_request: {}

concurrency:
  group: running-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Check for specific changes
    outputs:
      xcode: ${{ steps.xcode.outputs.matches }}
    steps:
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring xcodebuild
        id: xcode
        with:
          paths: Powercast/ Powercast.xcodeproj/ .github/workflows/xcodebuild.yml

  build:
    needs: changes
    if: needs.changes.outputs.xcode == 'true'
    uses: ./.github/workflows/xcodebuild.yml

  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make all
        shell: bash

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - build
      - make

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
