name: Tests

on:
  pull_request: {}

concurrency:
  group: running-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Check for specific changes
    outputs:
      xcode: ${{ steps.xcode.outputs.matches }}
      dependabot: ${{ steps.dependabot.outputs.matches }}
    steps:
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring xcodebuild
        id: xcode
        with:
          paths: Powercast/ Powercast.xcodeproj/ .github/workflows/xcodebuild.yml
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring validation of dependabot
        id: dependabot
        with:
          paths: .github/dependabot.yml .github/workflows/dependabot-validate.yml

  build:
    needs: changes
    if: needs.changes.outputs.xcode == 'true'
    uses: ./.github/workflows/xcodebuild.yml

  editorconfig:
    name: Editorconfig validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  make:
    uses: ./.github/workflows/make.yml

  dependabot:
    needs: changes
    if: needs.changes.outputs.dependabot == 'true'
    uses: ./.github/workflows/dependabot-validate.yml

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - build
      - editorconfig
      - make
      - dependabot

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
