name: Tests

on:
  pull_request: {}

concurrency:
  group: running-tests
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Check for specific changes
    outputs:
      xcode: ${{ steps.xcode.outputs.matches }}
      lint: ${{ steps.lint.outputs.matches }}
    steps:
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring xcodebuild
        id: xcode
        with:
          paths: Powercast/ Powercast.xcodeproj/ .github/workflows/xcodebuild.yml
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring linting
        id: lint
        with:
          paths: Powercast/ Powercast.xcodeproj/ .github/workflows/swiftlint.yml .swiftlint*
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring validation of dependabot
        id: dependabot
        with:
          paths: .github/dependabot.yml .github/workflows/dependabot-validate.yml
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring validation of lane
        id: lane
        with:
          paths: lanes resources .github/workflows/lane.yml

  build-test:
    needs: changes
    if: needs.changes.outputs.xcode == 'true'
    uses: ./.github/workflows/xcodebuild.yml

  swiftlint:
    needs: changes
    if: needs.changes.outputs.lint == 'true'
    uses: ./.github/workflows/swiftlint.yml

  editorconfig-check:
    name: Editorconfig check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  lane-check:
    needs: changes
    if: needs.changes.outputs.lane == 'true'
    uses: ./.github/workflows/lane.yml

  dependabot-validate:
    needs: changes
    if: needs.changes.outputs.dependabot == 'true'
    uses: ./.github/workflows/dependabot-validate.yml

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - build-test
      - swiftlint
      - editorconfig-check
      - lane-check
      - dependabot-validate

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
