name: Tests

on:
  pull_request: {}

concurrency:
  group: running-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Check for specific changes
    outputs:
      xcode: ${{ steps.xcode.outputs.matches }}
      lint: ${{ steps.lint.outputs.matches }}
      dependabot: ${{ steps.dependabot.outputs.matches }}
      lane: ${{ steps.lane.outputs.matches }}
    steps:
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring xcodebuild
        id: xcode
        with:
          paths: Powercast/ Powercast.xcodeproj/ .github/workflows/xcodebuild.yml
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring linting
        id: lint
        with:
          paths: Powercast/ Powercast.xcodeproj/ .github/workflows/swiftlint.yml .swiftlint*
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring validation of dependabot
        id: dependabot
        with:
          paths: .github/dependabot.yml .github/workflows/dependabot-validate.yml
      - uses: CodeReaper/find-diff-action@v3
        name: Changes requiring validation of lane
        id: lane
        with:
          paths: lanes resources .github/workflows/lane.yml

  build:
    needs: changes
    if: needs.changes.outputs.xcode == 'true'
    uses: ./.github/workflows/xcodebuild.yml

  swiftlint:
    needs: changes
    if: needs.changes.outputs.lint == 'true'
    uses: ./.github/workflows/swiftlint.yml

  editorconfig:
    name: Editorconfig validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  lane:
    needs: changes
    if: needs.changes.outputs.lane == 'true'
    uses: ./.github/workflows/lane.yml

  dependabot:
    needs: changes
    if: needs.changes.outputs.dependabot == 'true'
    uses: ./.github/workflows/dependabot-validate.yml

  translations:
    runs-on: ubuntu-latest
    name: Verify translations
    steps:
      - uses: actions/checkout@v4
      - name: Check for missing translations
        run: |
          find . -name "*.strings" -exec grep -Hin '= "";' {} \; > $$
          echo "Found missing translations:"
          cat $$
          test -s $$ && exit 1 || true

  gitstuff:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@v4
      - name: Git stuff
        env:
          GT_TOKEN: ${{ github.token }}
        run: |
          commits=$(gh api repos/${{ github.repository }}/commits?sha=main --paginate | jq length)
          echo "Number of commits: $commits"

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - build
      - swiftlint
      - editorconfig
      - lane
      - dependabot
      - translations

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
