name: Workflows

on:
  workflow_call: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
        with:
          tool_versions: |
            action-validator 0.6.0
      - name: Lint workflows
        run: find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) | xargs -I {} echo action-validator --verbose {} | sh -ex
        shell: bash
