name: xcodebuild

on:
  workflow_call: {}

jobs:
  xcodebuild:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cp Powercast/Local.xcconfig.sample Powercast/Local.xcconfig

          xcodebuild -project Powercast.xcodeproj \
          -scheme Powercast \
          -sdk iphonesimulator \
          -derivedDataPath './output' \
          build \
          CODE_SIGNING_ALLOWED=NO
