name: xcodebuild

on:
  workflow_call: {}

jobs:
  xcodebuild:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup local configuration
        run: cp Powercast/Local.xcconfig.sample Powercast/Local.xcconfig

      - name: Test
        run: |
          set -o pipefail && \
          xcodebuild -project Powercast.xcodeproj \
          -scheme Powercast \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' \
          test \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty

      - name: Build
        run: |
          set -o pipefail && \
          xcodebuild -project Powercast.xcodeproj \
          -scheme Powercast \
          -sdk iphonesimulator \
          -derivedDataPath './output' \
          build \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty
